# Generated by Django 5.0.3 on 2024-10-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(choices=[('aki', 'Aki'), ('blanka', 'Blanka'), ('cammy', 'Cammy'), ('chunli', 'Chunli'), ('dhalsim', 'Dhalsim'), ('dj', 'Dj'), ('ed', 'Ed'), ('gouki', 'Gouki'), ('guile', 'Guile'), ('honda', 'Honda'), ('jamie', 'Jamie'), ('jp', 'Jp'), ('juri', 'Juri'), ('ken', 'Ken'), ('kimbery', 'Kimbery'), ('lily', 'Lily'), ('luke', 'Luke'), ('manon', 'Manon'), ('marisa', 'Marisa'), ('rashid', 'Rashid'), ('ryu', 'Ryu'), ('terry', 'Terry'), ('vega', 'Vega'), ('zangief', 'Zangief')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('input_sequence', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(default='')),
                ('intro', models.TextField(default='')),
                ('body', models.TextField(default='')),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
