# Generated by Django 5.0.3 on 2024-11-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_character_rename_name_combo_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
