# Generated by Django 5.0.3 on 2024-11-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_combo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='frames',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='situation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
