# Generated by Django 5.0.3 on 2024-10-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(choices=[('aki', 'Aki'), ('blanka', 'Blanka'), ('cammy', 'Cammy')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('input_sequence', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
