# Generated by Django 5.0.3 on 2024-11-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_combo_frames_combo_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=6),
        ),
    ]
