# Generated by Django 5.0.3 on 2024-11-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_combo_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='frames',
        ),
    ]
