# Generated by Django 5.0.3 on 2024-11-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_combo_frames'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='input_type',
            field=models.CharField(choices=[('m', 'M'), ('c', 'C'), ('m & c', 'M & C')], default='m & c', max_length=50),
        ),
    ]
