# Generated by Django 5.0.3 on 2024-11-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_combo_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='difficulty',
            field=models.CharField(choices=[('easy', '初級'), ('medium', '中級'), ('hard', '上級')], default='初級', max_length=6),
        ),
    ]
