# Generated by Django 5.0.3 on 2025-02-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_combo_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='frames',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(choices=[('aki', 'Aki'), ('blanka', 'Blanka'), ('cammy', 'Cammy'), ('chunli', 'Chunli'), ('dhalsim', 'Dhalsim'), ('dj', 'Dj'), ('ed', 'Ed'), ('gouki', 'Gouki'), ('guile', 'Guile'), ('honda', 'Honda'), ('jamie', 'Jamie'), ('jp', 'Jp'), ('juri', 'Juri'), ('ken', 'Ken'), ('kimbery', 'Kimbery'), ('lily', 'Lily'), ('luke', 'Luke'), ('mai', 'Mai'), ('manon', 'Manon'), ('marisa', 'Marisa'), ('rashid', 'Rashid'), ('ryu', 'Ryu'), ('terry', 'Terry'), ('vega', 'Vega'), ('zangief', 'Zangief')], max_length=50),
        ),
    ]
