# Generated by Django 5.0.3 on 2025-02-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_combo_drive_combo_hit_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='Drive',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default='0'),
        ),
    ]
