# Generated by Django 5.0.3 on 2025-02-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_post_intro_remove_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='hit_situation',
            field=models.CharField(choices=[('normal', '通常以上'), ('only normal', '通常限定'), ('only counter', 'カウンター限定'), ('counter', 'カウンター以上限定'), ('only punish', 'パニカン限定')], default='通常以上', max_length=20),
        ),
    ]
