# Generated by Django 5.0.3 on 2025-02-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_combo_hit_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='character',
            field=models.CharField(choices=[('aki', 'Aki'), ('blanka', 'Blanka'), ('cammy', 'Cammy'), ('chunli', 'Chunli'), ('dhalsim', 'Dhalsim'), ('deejay', 'Deejay'), ('ed', 'Ed'), ('gouki', 'Gouki'), ('guile', 'Guile'), ('honda', 'Honda'), ('jamie', 'Jamie'), ('jp', 'Jp'), ('juri', 'Juri'), ('ken', 'Ken'), ('kimbery', 'Kimbery'), ('lily', 'Lily'), ('luke', 'Luke'), ('mai', 'Mai'), ('manon', 'Manon'), ('marisa', 'Marisa'), ('rashid', 'Rashid'), ('ryu', 'Ryu'), ('terry', 'Terry'), ('vega', 'Vega'), ('zangief', 'Zangief')], max_length=20),
        ),
        migrations.AlterField(
            model_name='combo',
            name='hit_situation',
            field=models.CharField(choices=[('normal', '通常'), ('counter', 'カウンター'), ('punish', 'パニカン')], default='通常', max_length=20),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
