# Generated by Django 5.0.3 on 2025-02-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_combo_character_alter_combo_hit_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='character',
            field=models.CharField(choices=[('ryu', 'Ryu'), ('aki', 'Aki'), ('blanka', 'Blanka'), ('cammy', 'Cammy'), ('chunli', 'Chunli'), ('dhalsim', 'Dhalsim'), ('deejay', 'Deejay'), ('ed', 'Ed'), ('gouki', 'Gouki'), ('guile', 'Guile'), ('honda', 'Honda'), ('jamie', 'Jamie'), ('jp', 'Jp'), ('juri', 'Juri'), ('ken', 'Ken'), ('kimbery', 'Kimbery'), ('lily', 'Lily'), ('luke', 'Luke'), ('mai', 'Mai'), ('manon', 'Manon'), ('marisa', 'Marisa'), ('rashid', 'Rashid'), ('terry', 'Terry'), ('vega', 'Vega'), ('zangief', 'Zangief')], max_length=20),
        ),
    ]
